### ISSUE TITLE
streamgift.netlify.app nya tidak bisa dipakai lagi?

### ISSUE THREAD

**Issue by cxionia** [IrPanK/stream-gift#1]
streamgift.netlify.app nya tidak bisa dipakai lagi? apakah sudah di nonaktifkan?
tidak bisa login kecuali menggunakan akun google, tapi setelah log in, lalu klik "ingin jadi streamer", klik yes dan yes lagi tidak mengarah kemana mana

**Comment by IrPanK** [comment]
Mohon maaf untuk sekarang streamgift.netlify.app sedang tidak bisa dipakai terlebih dahulu. Hal ini disebabkan service Heroku yang gratis sudah tidak tersedia. Mungkin ada saran untuk hostingan gratis lainnya, khususnya untuk bagian backend/servernya.

**Comment by IrPanK** [comment]
streamgift.netlify.app sudah bisa digunakan lagi ya

**Comment by cxionia** [comment]
terima kasih banyak untuk updatenya, kalau boleh tau menggunakan layanan hosting apa yang sekarang?

dan apakah bisa diupdate juga source codenya untuk yang sekarang?

**Comment by IrPanK** [comment]
Untuk layanan hosting sekarang menggunakan railway.app. Untuk source code tidak ada yang berubah signifikan, hanya penyesuaian terhadap endpointnya saja.

**Comment by cxionia** [comment]
terima kasih responnya, apa boleh minta link endpoint nya?

**Comment by IrPanK** [comment]
https://stream-gift-production.up.railway.app/

**Comment by cxionia** [comment]
streamgift.netlify.app tidak bisa berjalan lagi?
apakah karena layanan hosting railway.app nya sudah habis?
